const FIND_RESULTS = "FIND_RESULTS";
const SET_VALUE = "SET_VALUE";
const SET_MESSAGE = "SET_MESSAGE";
const CLEAR_VALUES = "CLEAR_VALUES";

export { FIND_RESULTS, SET_VALUE, SET_MESSAGE, CLEAR_VALUES };
